apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'prometheus'